### PR TITLE
solutions

### PR DESCRIPTION
**Pull request by hnguy96**

### CODE REVIEW

**Comment by hnguy96** [comment]
@Shubhamai sorry I'm new to this. How do I remove .DS_Store file?

**Comment by sophiabrandt** [comment]
@hnguy96
First, it's good practice to sync your repo to this repo. 
Add this repo as upstream (uses SSH, if you want to use HTTPS, you have to change the URL):
```bash
git remote add upstream git@github.com:zero-to-mastery/JS_Fun_Practice.git
```
Then `git pull upstream/master`, resolve any merge conflicts (use your search engine of choice to learn about merge conflicts). 

After your local repo is in sync again, delete the file on your local computer, then do `git add .DS_Store`.

After that `git status` to check if the only changed file is the `.DS_Store`.

Then push again to _your_ repository.

After that, do a pull request in the Github UI.

**Comment by hnguy96** [comment]
@sophiabrandt
Am I removing or adding `.DS_store`? I'm a bit confused.
But thank you for clarifying the rest! Really appreciate it.

**Comment by sophiabrandt** [comment]
Delete the file on your computer, but you have to tell git that you removed it. Thus, you have to do a `git add`.

**Pull request closed without merging**
